name: system-dev

services:
  backend:
    extends:
      file: ./backend/.docker/docker-compose.dev.yml
      service: app
    environment:
      - EXEC_MODE=dev
      - INFRA_MODE=integrated
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
    depends_on:
      firebase-emulator:
        condition: service_healthy

  frontend:
    extends:
      file: ./frontend/.docker/docker-compose.dev.yml
      service: app
    environment:
      - EXEC_MODE=dev
      - INFRA_MODE=integrated
      - BASE_PATH=/web
      - BACKEND_EXTERNAL_URL=${APP_URL:-http://localhost:3000}/api
      - NEXT_PUBLIC_USE_MOCKS=false
    depends_on:
      - backend

  gateway:
    depends_on:
      - backend
      - frontend

include:
  - path: ./firebase-emulator/docker-compose.yml
  - path: ./gateway/docker-compose.yml
