
services:
  app:
    networks:
      default:
        aliases:
          - backend
    environment:
      - INFRA_MODE=integrated
      - FILESYSTEM_URL=http://filesystem:3001
networks:
  default:
    name: global_mesh
    external: true
