services:
  app: 
    build:
      context: .
      target: dev
    env_file:
      - path: .env.dev
        required: false
    volumes:
      - .:/app
    environment:
      - INFRA_MODE=isolated
      - EXEC_MODE=dev
