services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    build:
      target: dev
    volumes:
      - ..:/app 
      - /app/node_modules
    env_file:
      - ../.env.dev 
    environment:
      - INFRA_MODE=integrated
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
    depends_on:
      firebase-emulator:
        condition: service_healthy
