services:
  app:
    extends:
      file: ./docker-compose.yml
      service: app
    build: 
      target: prod
    env_file:
      - ../.env.test
    environment:
      - INFRA_MODE=integrated
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
    depends_on:
      firebase-emulator:
        condition: service_healthy

  test-unit:
    profiles:
      - unit
    build:
      context: ..
      target: test
    env_file:
      - ../.env.test 

  test-e2e:
    build:
      context: ..
      target: test-e2e
    env_file:
      - ../.env.test
    environment: 
      - API_URL=http://app:${PORT:-3000}
    depends_on:
      app:
        condition: service_healthy
