services:
  test-unit:
    build: 
      context: .
      target: test
    env_file:
      - path: .env.test
        required: false
    environment:
      - NODE_ENV=test
      - CI=true
    restart: "no"