services: 
  test-e2e:
    build: 
      context: .
      target: test-e2e
    env_file:
      - path: .env.test
        required: false
    environment: 
      - API_URL=http://app:${PORT:-3000}
    restart: "no"
    depends_on:
      app:
        condition: service_healthy
